disabled_rules: # rule identifiers to exclude from running
  - line_length
  - trailing_whitespace
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)