source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MJSnackBar_Example', :exclusive => true do
  pod 'MJSnackBar', :path => '../'
end

target 'MJSnackBar_Tests', :exclusive => true do
  pod 'MJSnackBar', :path => '../'

  
end
